import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const supportedLocales = [Locale('en'), Locale('te')];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        const AppLocalizations(Locale('en'));
  }

  String t(String key) {
    final languageCode = locale.languageCode;
    return _couponLocalizedValues[languageCode]?[key] ??
        _additionalLocalizedValues[languageCode]?[key] ??
        _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  String translateText(String text) => t(text);

  String get appTitle => t('Lakshya Smartguard systems');
  String get language => t('Language');
  String get english => t('English');
  String get telugu => t('Telugu');
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String tr(String key) => AppLocalizations.of(this).t(key);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (supported) => supported.languageCode == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

const Map<String, Map<String, String>> _additionalLocalizedValues = {
  'en': {
    'Coupon Management': 'Coupon Management',
    'Create and manage retailer coupons': 'Create and manage retailer coupons',
    'Create Coupon': 'Create Coupon',
    'Edit Coupon': 'Edit Coupon',
    'Update Coupon': 'Update Coupon',
    'No coupons found': 'No coupons found',
    'Coupon Code': 'Coupon Code',
    'e.g. SPRAY10': 'e.g. SPRAY10',
    'Discount Type': 'Discount Type',
    'Percentage': 'Percentage',
    'Fixed': 'Fixed',
    'Discount Value': 'Discount Value',
    'Valid From': 'Valid From',
    'Valid Until': 'Valid Until',
    'Maximum Usage': 'Maximum Usage',
    'Remaining Usage': 'Remaining Usage',
    'Eligible Service': 'Eligible Service',
    'e.g. Drone Spraying': 'e.g. Drone Spraying',
    'Applicable Region': 'Applicable Region',
    'e.g. Telangana': 'e.g. Telangana',
    'Assigned Retailers': 'Assigned Retailers',
    'Active Status': 'Active Status',
    'Select Date': 'Select Date',
    'Discount': 'Discount',
    'Usage': 'Usage',
    'Active': 'Active',
    'Inactive': 'Inactive',
    'Activate': 'Activate',
    'Deactivate': 'Deactivate',
    'Edit': 'Edit',
    'Delete': 'Delete',
    'Delete Coupon': 'Delete Coupon',
    'Are you sure you want to delete this coupon?':
        'Are you sure you want to delete this coupon?',
    'Coupon code already exists.': 'Coupon code already exists.',
    'Please select valid dates.': 'Please select valid dates.',
    'Valid until must be after valid from.':
        'Valid until must be after valid from.',
    'Please assign at least one retailer.':
        'Please assign at least one retailer.',
    'Must be greater than 0': 'Must be greater than 0',
    'Remaining usage cannot exceed maximum usage':
        'Remaining usage cannot exceed maximum usage',
    'Coupon created successfully': 'Coupon created successfully',
    'Coupon updated successfully': 'Coupon updated successfully',
    'Percentage discount cannot exceed 100%':
        'Percentage discount cannot exceed 100%',
  },
  'te': {
    'Hello': 'హలో',
    'Good Morning!': 'శుభోదయం!',
    'Good Afternoon!': 'శుభ మధ్యాహ్నం!',
    'Good Evening!': 'శుభ సాయంత్రం!',
    'Notifications': 'నోటిఫికేషన్లు',
    'Farms': 'పొలాలు',
    'Assignments': 'కేటాయింపులు',
    'Farmers': 'రైతులు',
    'Retailer': 'రిటైలర్',
    'Retailer Management': 'రిటైలర్ నిర్వహణ',
    'Search retailers...': 'రిటైలర్లను వెతకండి...',
    'No retailers found': 'రిటైలర్లు కనబడలేదు',
    'View Details': 'వివరాలు చూడండి',
    'Approve': 'ఆమోదించు',
    'Reject': 'తిరస్కరించు',
    'Suspend': 'నిలిపివేయి',
    'Reactivate': 'మళ్లీ సక్రియం చేయి',
    'Owner': 'యజమాని',
    'Mobile': 'మొబైల్',
    'GST': 'జీఎస్టీ',
    'Aadhaar/PAN': 'ఆధార్/పాన్',
    'Address': 'చిరునామా',
    'Location': 'స్థానం',
    'GPS': 'జీపీఎస్',
    'ACTIVE': 'సక్రియం',
    'INACTIVE': 'నిష్క్రియం',
    'APPROVED': 'ఆమోదించబడింది',
    'PENDING': 'పెండింగ్',
    'REJECTED': 'తిరస్కరించబడింది',
    'SUSPENDED': 'నిలిపివేయబడింది',
    'Add New Farm': 'కొత్త పొలం జోడించండి',
    'Edit Farm': 'పొలం సవరించండి',
    'Farm Name *': 'పొలం పేరు *',
    'e.g. Green Valley Farm': 'ఉదా. గ్రీన్ వ్యాలీ ఫార్మ్',
    'Farm name is required': 'పొలం పేరు అవసరం',
    'Crop Type *': 'పంట రకం *',
    'Cotton': 'పత్తి',
    'Paddy': 'వరి',
    'Chilli': 'మిరప',
    'Maize': 'మొక్కజొన్న',
    'Soya': 'సోయా',
    'Other': 'ఇతర',
    'Other Crop Type *': 'ఇతర పంట రకం *',
    'Enter crop name': 'పంట పేరు నమోదు చేయండి',
    'Crop name is required': 'పంట పేరు అవసరం',
    'Area *': 'విస్తీర్ణం *',
    'Required': 'అవసరం',
    'Unit': 'యూనిట్',
    'Hectares': 'హెక్టార్లు',
    'Village *': 'గ్రామం *',
    'Enter village': 'గ్రామం నమోదు చేయండి',
    'Village is required': 'గ్రామం అవసరం',
    'District *': 'జిల్లా *',
    'Enter district': 'జిల్లా నమోదు చేయండి',
    'District is required': 'జిల్లా అవసరం',
    'State *': 'రాష్ట్రం *',
    'Enter state': 'రాష్ట్రం నమోదు చేయండి',
    'State is required': 'రాష్ట్రం అవసరం',
    'Farm Location *': 'పొలం స్థానం *',
    'Location Selected': 'స్థానం ఎంపికైంది',
    'Select Location on Map': 'మ్యాప్‌లో స్థానం ఎంచుకోండి',
    'Please select farm location on map':
        'దయచేసి మ్యాప్‌లో పొలం స్థానాన్ని ఎంచుకోండి',
    'Update Farm': 'పొలం నవీకరించండి',
    'Save Farm': 'పొలం సేవ్ చేయండి',
    'Register Farmer': 'రైతును నమోదు చేయండి',
    'My Farmers': 'నా రైతులు',
    'Search Farmer': 'రైతును వెతకండి',
    'Book Service': 'సేవ బుక్ చేయండి',
    'Booking History': 'బుకింగ్ చరిత్ర',
    'Payment Status': 'చెల్లింపు స్థితి',
    'Manage farmers and bookings.': 'రైతులు మరియు బుకింగ్‌లను నిర్వహించండి.',
    'Payment status will appear with booking records.':
        'బుకింగ్ రికార్డులతో చెల్లింపు స్థితి కనిపిస్తుంది.',
    'Retailer notifications are delivered by the app.':
        'రిటైలర్ నోటిఫికేషన్లు యాప్ ద్వారా అందించబడతాయి.',
    'Wait for Admin Approval': 'అడ్మిన్ ఆమోదం కోసం వేచి ఉండండి',
    'External Pilot Approvals': 'బాహ్య పైలట్ ఆమోదాలు',
    'Pilot Earnings & Incentives': 'పైలట్ ఆదాయం మరియు ప్రోత్సాహకాలు',
    'Current Earnings': 'ప్రస్తుత ఆదాయం',
    'View Wallet': 'వాలెట్ చూడండి',
    'Cash Collection': 'నగదు సేకరణ',
    'No cash pending deposit.': 'డిపాజిట్ పెండింగ్‌లో ఉన్న నగదు లేదు.',
    'Mark as Deposited': 'డిపాజిట్ చేసినట్లు గుర్తించు',
    'Just now': 'ఇప్పుడే',
    'm ago': 'నిమిషాల క్రితం',
    'h ago': 'గంటల క్రితం',
    'Yesterday': 'నిన్న',
    'Farmer: ': 'రైతు: ',
    'Operational Overview': 'కార్యాచరణ అవలోకనం',
    'All Bookings': 'అన్ని బుకింగ్స్',
    'Reported Issues': 'నివేదించబడిన సమస్యలు',
    'Review Bookings': 'బుకింగ్లను సమీక్షించండి',
    'Assign Pilot': 'పైలట్‌ను కేటాయించండి',
    'Recent Bookings': 'ఇటీవలి బుకింగ్స్',
    'No bookings found.': 'బుకింగ్స్ ఏవీ కనబడలేదు.',
    'Verify and approve new requests': 'కొత్త అభ్యర్థనలను ధృవీకరించండి మరియు ఆమోదించండి',
    'Match pilots with approved bookings': 'పైలట్లను ఆమోదించిన బుకింగ్‌లతో సరిపోల్చండి',
    'Manage and review bookings.': 'బుకింగ్‌లను నిర్వహించండి మరియు సమీక్షించండి.',
    'Search ID, Farmer, Farm...': 'ఐడి, రైతు, పొలం కోసం వెతకండి...',
    'Reset All': 'అన్నీ రీసెట్ చేయండి',
    'Filter & Sort': 'ఫిల్టర్ & క్రమబద్ధీకరించు',
    'Sort By': 'క్రమబద్ధీకరించు',
    'Newest First': 'కొత్తవి ముందు',
    'Oldest First': 'పాతవి ముందు',
    'Pending Review': 'పెండింగ్ సమీక్ష',
    'Approved': 'ఆమోదించబడింది',
    'Active Missions': 'క్రియాశీల పనులు',
    'Completed Today': 'ఈరోజు పూర్తయినవి',
    'Acres Completed': 'పూర్తయిన ఎకరాలు',
    'Send Notifications': 'నోటిఫికేషన్లు పంపండి',
    'Broadcast messages or alert users': 'వినియోగదారులకు సందేశాలు లేదా హెచ్చరికలను పంపండి',
    'Pilot Contact': 'పైలట్ సంప్రదింపు సంఖ్య',
    'Pilot Contact: ': 'పైలట్ సంప్రదింపు సంఖ్య: ',
    'Not Provided': 'అందించబడలేదు',
    'Note': 'గమనిక',
    'Note: ': 'గమనిక: ',
    'acres': 'ఎకరాలు',
    'Acres': 'ఎకరాలు',
    'Ac': 'ఎకరాలు',
    'Booking ID': 'బుకింగ్ ఐడి',
    'All': 'అన్నీ',
    'Issues': 'సమస్యలు',
    'Confirm Assignment': 'కేటాయింపును నిర్ధారించండి',
    'Pilot Selection (Required)': 'పైలట్ ఎంపిక (తప్పనిసరి)',
    'No available pilots': 'అందుబాటులో పైలట్లు లేరు',
    'Active available pilots will appear here.': 'క్రియాశీల అందుబాటులో ఉన్న పైలట్లు ఇక్కడ కనిపిస్తారు.',
    'Unable to load pilots': 'పైలట్లను లోడ్ చేయడం సాధ్యం కాలేదు',
    'Check your connection and try again.': 'మీ కనెక్షన్ తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.',
    'Copilot (Optional)': 'సహ పైలట్ (ఐచ్ఛికం)',
    'Leave empty if this booking does not require a Copilot.': 'ఈ బుకింగ్‌కు సహ పైలట్ అవసరం లేకపోతే ఖాళీగా వదిలేయండి.',
    'No available copilots': 'అందుబాటులో సహ పైలట్లు లేరు',
    'Super Admin': 'సూపర్ అడ్మిన్',
    'Pesticide Spraying': 'పురుగుమందుల పిచికారీ',
    'Fungicide Spraying': 'శిలీంద్రనాశక పిచికారీ',
    'Farmer Information': 'రైతు సమాచారం',
    'Farmer Name': 'రైతు పేరు',
    'Phone Number': 'ఫోన్ నంబర్',
    'Farm Information': 'పొలం సమాచారం',
    'Farm Name': 'పొలం పేరు',
    'Service Requested': 'కోరిన సేవ',
    'Preferred Date': 'కోరుకున్న తేదీ',
    'Preferred Time': 'కోరుకున్న సమయం',
    'Assigned Pilot': 'కేటాయించిన పైలట్',
    'Coupon & Verification': 'కూపన్ & ధృవీకరణ',
    'Internal Pilot': 'అంతర్గత పైలట్',
    'Available': 'అందుబాటులో ఉంది',
    'active jobs': 'క్రియాశీల పనులు',
    'Select Copilot': 'సహ పైలట్‌ను ఎంచుకోండి',
    'Clear': 'రద్దు చేయి',
    'Pilot and Copilot must be different employees.': 'పైలట్ మరియు సహ పైలట్ వేర్వేరు ఉద్యోగులు ఉండాలి.',
    'Pilot assigned successfully': 'పైలట్ విజయవంతంగా కేటాయించబడ్డారు',
    'Booking': 'బుకింగ్',
    'Copilot': 'సహ పైలట్',
    'Status': 'స్థితి',
    'Crop Type': 'పంట రకం',
    'Not provided': 'అందించబడలేదు',
    'Booking Details': 'బుకింగ్ వివరాలు',
    'Booking not found': 'బుకింగ్ కనుగొనబడలేదు',
    'Error loading details': 'వివరాలను లోడ్ చేయడంలో లోపం',
  },
};

const Map<String, Map<String, String>> _couponLocalizedValues = {
  'te': {
    'Coupon Management': 'కూపన్ నిర్వహణ',
    'Create and manage retailer coupons':
        'రిటైలర్ కూపన్లను సృష్టించి నిర్వహించండి',
    'Create Coupon': 'కూపన్ సృష్టించండి',
    'Edit Coupon': 'కూపన్ సవరించండి',
    'Update Coupon': 'కూపన్ నవీకరించండి',
    'No coupons found': 'కూపన్లు కనబడలేదు',
    'Coupon Code': 'కూపన్ కోడ్',
    'e.g. SPRAY10': 'ఉదా. SPRAY10',
    'Discount Type': 'డిస్కౌంట్ రకం',
    'Percentage': 'శాతం',
    'Fixed': 'నిర్దిష్టం',
    'Discount Value': 'డిస్కౌంట్ విలువ',
    'Valid From': 'చెల్లుబాటు ప్రారంభం',
    'Valid Until': 'చెల్లుబాటు ముగింపు',
    'Maximum Usage': 'గరిష్ఠ వినియోగం',
    'Remaining Usage': 'మిగిలిన వినియోగం',
    'Eligible Service': 'అర్హమైన సేవ',
    'e.g. Drone Spraying': 'ఉదా. డ్రోన్ స్ప్రేయింగ్',
    'Applicable Region': 'వర్తించే ప్రాంతం',
    'e.g. Telangana': 'ఉదా. తెలంగాణ',
    'Assigned Retailers': 'కేటాయించిన రిటైలర్లు',
    'Active Status': 'సక్రియ స్థితి',
    'Select Date': 'తేదీ ఎంచుకోండి',
    'Discount': 'డిస్కౌంట్',
    'Usage': 'వినియోగం',
    'Active': 'సక్రియం',
    'Inactive': 'నిష్క్రియం',
    'Activate': 'సక్రియం చేయి',
    'Deactivate': 'నిష్క్రియం చేయి',
    'Edit': 'సవరించు',
    'Delete': 'తొలగించు',
    'Delete Coupon': 'కూపన్ తొలగించు',
    'Are you sure you want to delete this coupon?':
        'మీరు ఈ కూపన్‌ను ఖచ్చితంగా తొలగించాలనుకుంటున్నారా?',
    'Coupon code already exists.': 'కూపన్ కోడ్ ఇప్పటికే ఉంది.',
    'Please select valid dates.': 'దయచేసి చెల్లుబాటు అయ్యే తేదీలను ఎంచుకోండి.',
    'Valid until must be after valid from.':
        'ముగింపు తేదీ ప్రారంభ తేదీ తర్వాత ఉండాలి.',
    'Please assign at least one retailer.':
        'దయచేసి కనీసం ఒక రిటైలర్‌ను కేటాయించండి.',
    'Must be greater than 0': '0 కంటే ఎక్కువ ఉండాలి',
    'Remaining usage cannot exceed maximum usage':
        'మిగిలిన వినియోగం గరిష్ఠ వినియోగాన్ని మించకూడదు',
    'Coupon created successfully': 'కూపన్ విజయవంతంగా సృష్టించబడింది',
    'Coupon updated successfully': 'కూపన్ విజయవంతంగా నవీకరించబడింది',
    'Percentage discount cannot exceed 100%':
        'శాతం డిస్కౌంట్ 100% మించకూడదు',
  },
};

const Map<String, Map<String, String>> _localizedValues = {
  'en': {
    'Lakshya Smartguard systems': 'Lakshya Smartguard systems',
    'Login': 'Login',
    'Logout': 'Logout',
    'Are you sure you want to log out?': 'Are you sure you want to log out?',
    'Cancel': 'Cancel',
    'Confirm': 'Confirm',
    'Profile': 'Profile',
    'Settings': 'Settings',
    'Language': 'Language',
    'English': 'English',
    'Telugu': 'Telugu',
    'Edit Profile': 'Edit Profile',
    'Change Password': 'Change Password',
    'App Information': 'App Information',
    'Account Information': 'Account Information',
    'Phone': 'Phone',
    'Email': 'Email',
    'Village': 'Village',
    'District': 'District',
    'Member Since': 'Member Since',
    'Dashboard': 'Dashboard',
    'Employees': 'Employees',
    'Bookings': 'Bookings',
    'Home': 'Home',
    'Jobs': 'Jobs',
    'History': 'History',
    'Overview': 'Overview',
    'Quick Actions': 'Quick Actions',
    'Recent Activity': 'Recent Activity',
    'View All': 'View All',
    'All Recent Activity': 'All Recent Activity',
    'No recent activity': 'No recent activity',
    'Activities will appear here when the team starts using the app.':
        'Activities will appear here when the team starts using the app.',
    'Execution Overview': 'Execution Overview',
    'Today': 'Today',
    'Pending': 'Pending',
    'Completed': 'Completed',
    'Acres': 'Acres',
    'Active Mission': 'Active Mission',
    'No active mission.': 'No active mission.',
    'Overall Pilot Stats': 'Overall Pilot Stats',
    'Total Flight Hours': 'Total Flight Hours',
    'Total Missions': 'Total Missions',
    'My Jobs': 'My Jobs',
    'Assigned': 'Assigned',
    'In Progress': 'In Progress',
    'No jobs found': 'No jobs found',
    'Check back later for new assignments.':
        'Check back later for new assignments.',
    'Precision Spraying': 'Precision Spraying',
    'Better Yield': 'Better Yield',
    'Healthy Fields': 'Healthy Fields',
    'Book Now': 'Book Now',
    'Book New Service': 'Book New Service',
    'My Bookings': 'My Bookings',
    'My Farms': 'My Farms',
    'Service History': 'Service History',
    'Upcoming Booking': 'Upcoming Booking',
    'No upcoming bookings': 'No upcoming bookings',
    'Book a Service Now': 'Book a Service Now',
    'Total Farms': 'Total Farms',
    'Total Bookings': 'Total Bookings',
    'Total Acres': 'Total Acres',
    'Pending Bookings': 'Pending Bookings',
    'Add Employee': 'Add Employee',
    'Manage Employees': 'Manage Employees',
    'Manage Drones': 'Manage Drones',
    'Analytics & Reports': 'Analytics & Reports',
    'Admin Details': 'Admin Details',
    'Employee ID': 'Employee ID',
    'Admin Level': 'Admin Level',
    'Created Date': 'Created Date',
    'Farm Activity': 'Farm Activity',
    'Execution Stats': 'Execution Stats',
    'Missions': 'Missions',
    'Flight Hours': 'Flight Hours',
    'Avg Rating': 'Avg Rating',
    'Assignment': 'Assignment',
    'Current Drone': 'Current Drone',
    'Operations': 'Operations',
    'Bookings Handled': 'Bookings Handled',
    'Assigned Region': 'Assigned Region',
    'N/A': 'N/A',
    'User Name': 'User Name',
    'Admin': 'Admin',
    'Farmer': 'Farmer',
    'Pilot': 'Pilot',
    'Operations Member': 'Operations Member',
    'Password reset link sent to your email.':
        'Password reset link sent to your email.',
    'Unauthorized employee.': 'Unauthorized employee.',
    'Your account has been disabled. Please contact the administrator.':
        'Your account has been disabled. Please contact the administrator.',
    'The email address is badly formatted.':
        'The email address is badly formatted.',
    'No user found with this email.': 'No user found with this email.',
    'Incorrect password.': 'Incorrect password.',
    'Invalid credentials. Please check your email and password.':
        'Invalid credentials. Please check your email and password.',
    'Too many attempts. Please try again later.':
        'Too many attempts. Please try again later.',
    'Network request failed. Please check your connection.':
        'Network request failed. Please check your connection.',
    'The phone number is invalid.': 'The phone number is invalid.',
    'The OTP entered is incorrect.': 'The OTP entered is incorrect.',
    'An unknown error occurred.': 'An unknown error occurred.',
    'Reviewed': 'Reviewed',
    'Pilot Assigned': 'Pilot Assigned',
    'Drone Assigned': 'Drone Assigned',
    'Accepted': 'Accepted',
    'En Route': 'En Route',
    'Arrived': 'Arrived',
    'Confirmed': 'Confirmed',
    'Closed': 'Closed',
    'Issue Reported': 'Issue Reported',
    'Cancelled': 'Cancelled',
    'Hello': 'Hello',
    'Good Morning!': 'Good Morning!',
    'Good Afternoon!': 'Good Afternoon!',
    'Good Evening!': 'Good Evening!',
    'Notifications': 'Notifications',
    'Farms': 'Farms',
    'Assignments': 'Assignments',
    'Farmers': 'Farmers',
    'Retailer': 'Retailer',
    'Retailer Management': 'Retailer Management',
    'Search retailers...': 'Search retailers...',
    'No retailers found': 'No retailers found',
    'View Details': 'View Details',
    'Approve': 'Approve',
    'Reject': 'Reject',
    'Suspend': 'Suspend',
    'Reactivate': 'Reactivate',
    'Owner': 'Owner',
    'Mobile': 'Mobile',
    'GST': 'GST',
    'Aadhaar/PAN': 'Aadhaar/PAN',
    'Address': 'Address',
    'Location': 'Location',
    'GPS': 'GPS',
    'ACTIVE': 'ACTIVE',
    'INACTIVE': 'INACTIVE',
    'APPROVED': 'APPROVED',
    'PENDING': 'PENDING',
    'REJECTED': 'REJECTED',
    'SUSPENDED': 'SUSPENDED',
    'Add New Farm': 'Add New Farm',
    'Edit Farm': 'Edit Farm',
    'Farm Name *': 'Farm Name *',
    'e.g. Green Valley Farm': 'e.g. Green Valley Farm',
    'Farm name is required': 'Farm name is required',
    'Crop Type *': 'Crop Type *',
    'Cotton': 'Cotton',
    'Paddy': 'Paddy',
    'Chilli': 'Chilli',
    'Maize': 'Maize',
    'Soya': 'Soya',
    'Other': 'Other',
    'Other Crop Type *': 'Other Crop Type *',
    'Enter crop name': 'Enter crop name',
    'Crop name is required': 'Crop name is required',
    'Area *': 'Area *',
    'Required': 'Required',
    'Unit': 'Unit',
    'Hectares': 'Hectares',
    'Village *': 'Village *',
    'Enter village': 'Enter village',
    'Village is required': 'Village is required',
    'District *': 'District *',
    'Enter district': 'Enter district',
    'District is required': 'District is required',
    'State *': 'State *',
    'Enter state': 'Enter state',
    'State is required': 'State is required',
    'Farm Location *': 'Farm Location *',
    'Location Selected': 'Location Selected',
    'Select Location on Map': 'Select Location on Map',
    'Please select farm location on map': 'Please select farm location on map',
    'Update Farm': 'Update Farm',
    'Save Farm': 'Save Farm',
    'Register Farmer': 'Register Farmer',
    'My Farmers': 'My Farmers',
    'Search Farmer': 'Search Farmer',
    'Book Service': 'Book Service',
    'Booking History': 'Booking History',
    'Payment Status': 'Payment Status',
    'Manage farmers and bookings.': 'Manage farmers and bookings.',
    'Payment status will appear with booking records.':
        'Payment status will appear with booking records.',
    'Retailer notifications are delivered by the app.':
        'Retailer notifications are delivered by the app.',
  },
  'te': {
    'Lakshya Smartguard systems': 'లక్ష్య స్మార్ట్‌గార్డ్ సిస్టమ్స్',
    'Login': 'లాగిన్',
    'Logout': 'లాగ్ అవుట్',
    'Are you sure you want to log out?':
        'మీరు ఖచ్చితంగా లాగ్ అవుట్ చేయాలనుకుంటున్నారా?',
    'Cancel': 'రద్దు',
    'Confirm': 'నిర్ధారించు',
    'Profile': 'ప్రొఫైల్',
    'Settings': 'సెట్టింగ్స్',
    'Language': 'భాష',
    'English': 'ఆంగ్లం',
    'Telugu': 'తెలుగు',
    'Edit Profile': 'ప్రొఫైల్ సవరించు',
    'Change Password': 'పాస్వర్డ్ మార్చు',
    'App Information': 'యాప్ సమాచారం',
    'Account Information': 'ఖాతా సమాచారం',
    'Phone': 'ఫోన్',
    'Email': 'ఈమెయిల్',
    'Village': 'గ్రామం',
    'District': 'జిల్లా',
    'Member Since': 'సభ్యత్వం ప్రారంభం',
    'Dashboard': 'డ్యాష్ బోర్డ్',
    'Employees': 'ఉద్యోగులు',
    'Bookings': 'బుకింగ్స్',
    'Home': 'హోమ్',
    'Jobs': 'పనులు',
    'History': 'చరిత్ర',
    'Overview': 'అవలోకనం',
    'Quick Actions': 'త్వరిత చర్యలు',
    'Recent Activity': 'తాజా కార్యకలాపాలు',
    'View All': 'అన్నీ చూడండి',
    'All Recent Activity': 'అన్ని తాజా కార్యకలాపాలు',
    'No recent activity': 'తాజా కార్యకలాపాలు లేవు',
    'Activities will appear here when the team starts using the app.':
        'బృందం యాప్ ఉపయోగించడం ప్రారంభించినప్పుడు కార్యకలాపాలు ఇక్కడ కనిపిస్తాయి.',
    'Execution Overview': 'అమలు అవలోకనం',
    'Today': 'ఈ రోజు',
    'Pending': 'పెండింగ్',
    'Completed': 'పూర్తయింది',
    'Acres': 'ఎకరాలు',
    'Active Mission': 'క్రియాశీల మిషన్',
    'No active mission.': 'క్రియాశీల మిషన్ లేదు.',
    'Overall Pilot Stats': 'మొత్తం పైలట్ గణాంకాలు',
    'Total Flight Hours': 'మొత్తం విమాన గంటలు',
    'Total Missions': 'మొత్తం మిషన్లు',
    'My Jobs': 'నా పనులు',
    'Assigned': 'కేటాయించబడింది',
    'In Progress': 'ప్రగతిలో ఉంది',
    'No jobs found': 'పనులు కనబడలేదు',
    'Check back later for new assignments.':
        'కొత్త కేటాయింపుల కోసం తరువాత చూడండి.',
    'Precision Spraying': 'ఖచ్చితమైన స్ప్రేయింగ్',
    'Better Yield': 'మెరుగైన దిగుబడి',
    'Healthy Fields': 'ఆరోగ్యకరమైన పొలాలు',
    'Book Now': 'ఇప్పుడే బుక్ చేయండి',
    'Book New Service': 'కొత్త సేవ బుక్ చేయండి',
    'My Bookings': 'నా బుకింగ్స్',
    'My Farms': 'నా పొలాలు',
    'Service History': 'సేవల చరిత్ర',
    'Upcoming Booking': 'రాబోయే బుకింగ్',
    'No upcoming bookings': 'రాబోయే బుకింగ్స్ లేవు',
    'Book a Service Now': 'ఇప్పుడే సేవ బుక్ చేయండి',
    'Total Farms': 'మొత్తం పొలాలు',
    'Total Bookings': 'మొత్తం బుకింగ్స్',
    'Total Acres': 'మొత్తం ఎకరాలు',
    'Pending Bookings': 'పెండింగ్ బుకింగ్స్',
    'Add Employee': 'ఉద్యోగిని జోడించు',
    'Manage Employees': 'ఉద్యోగులను నిర్వహించు',
    'Manage Drones': 'డ్రోన్లను నిర్వహించు',
    'Analytics & Reports': 'విశ్లేషణలు మరియు నివేదికలు',
    'Admin Details': 'అడ్మిన్ వివరాలు',
    'Employee ID': 'ఉద్యోగి ఐడి',
    'Admin Level': 'అడ్మిన్ స్థాయి',
    'Created Date': 'సృష్టించిన తేదీ',
    'Farm Activity': 'పొలం కార్యకలాపాలు',
    'Execution Stats': 'అమలు గణాంకాలు',
    'Missions': 'మిషన్లు',
    'Flight Hours': 'విమాన గంటలు',
    'Avg Rating': 'సగటు రేటింగ్',
    'Assignment': 'కేటాయింపు',
    'Current Drone': 'ప్రస్తుత డ్రోన్',
    'Operations': 'ఆపరేషన్స్',
    'Bookings Handled': 'నిర్వహించిన బుకింగ్స్',
    'Assigned Region': 'కేటాయించిన ప్రాంతం',
    'N/A': 'వర్తించదు',
    'User Name': 'వినియోగదారు పేరు',
    'Admin': 'అడ్మిన్',
    'Farmer': 'రైతు',
    'Pilot': 'పైలట్',
    'Operations Member': 'ఆపరేషన్స్ సభ్యుడు',
    'Password reset link sent to your email.':
        'పాస్వర్డ్ రీసెట్ లింక్ మీ ఈమెయిల్ కు పంపబడింది.',
    'Unauthorized employee.': 'అనధికార ఉద్యోగి.',
    'Your account has been disabled. Please contact the administrator.':
        'మీ ఖాతా నిలిపివేయబడింది. దయచేసి నిర్వాహకుడిని సంప్రదించండి.',
    'The email address is badly formatted.':
        'ఈమెయిల్ చిరునామా సరైన ఫార్మాట్ లో లేదు.',
    'No user found with this email.': 'ఈ ఈమెయిల్ తో వినియోగదారు లేరు.',
    'Incorrect password.': 'తప్పు పాస్వర్డ్.',
    'Invalid credentials. Please check your email and password.':
        'చెల్లని వివరాలు. మీ ఈమెయిల్ మరియు పాస్వర్డ్ తనిఖీ చేయండి.',
    'Too many attempts. Please try again later.':
        'చాలా ప్రయత్నాలు చేశారు. దయచేసి తరువాత ప్రయత్నించండి.',
    'Network request failed. Please check your connection.':
        'నెట్ వర్క్ అభ్యర్థన విఫలమైంది. మీ కనెక్షన్ తనిఖీ చేయండి.',
    'The phone number is invalid.': 'ఫోన్ నంబర్ చెల్లదు.',
    'The OTP entered is incorrect.': 'నమోదు చేసిన ఓటిపి తప్పు.',
    'An unknown error occurred.': 'తెలియని లోపం జరిగింది.',
    'Reviewed': 'సమీక్షించబడింది',
    'Pilot Assigned': 'పైలట్ కేటాయించబడింది',
    'Drone Assigned': 'డ్రోన్ కేటాయించబడింది',
    'Accepted': 'అంగీకరించబడింది',
    'En Route': 'మార్గంలో ఉంది',
    'Arrived': 'చేరుకుంది',
    'Confirmed': 'నిర్ధారించబడింది',
    'Closed': 'ముగిసింది',
    'Issue Reported': 'సమస్య నివేదించబడింది',
    'Cancelled': 'రద్దు చేయబడింది',
    'Farms': 'పొలాలు',
    // 'My Farms': 'నా పొలాలు',
    'Add Farm': 'పొలాన్ని జోడించండి',
    'Manage all your registered farms.': 'మీ అన్ని నమోదిత పొలాలను నిర్వహించండి.',
    'Search by name, village...': 'పేరు, గ్రామం ద్వారా శోధించండి...',
    'Search farm or ID...': 'పొలం లేదా ఐడి శోధించండి...',
    'New Booking': 'కొత్త బుకింగ్',
    'Current & Completed Missions': 'ప్రస్తుత & పూర్తయిన పనులు',
    'Upcoming Assignments': 'రాబోయే పనులు',
    'Booking History': 'బుకింగ్ చరిత్ర',
    'Filter & Sort': 'ఫిల్టర్ & క్రమబద్ధీకరించు',
    'Clear Filters': 'ఫిల్టర్లను క్లియర్ చేయి',
    // 'Pending': 'పెండింగ్',
    'Upcoming': 'రాబోయే పనులు',
    'Active': 'క్రియాశీల',
    // 'Completed': 'పూర్తయింది',
    'No bookings found.': 'బుకింగ్స్ ఏవీ కనబడలేదు.',
    'Try adjusting your search or filters.': 'మీ శోధన లేదా ఫిల్టర్లను సర్దుబాటు చేయడానికి ప్రయత్నించండి.',
    'Cotton': 'పత్తి',
    'Paddy': 'వరి',
    'Chilli': 'మిరప',
    'Maize': 'మొక్కజొన్న',
    'Soya': 'సోయా',
    'Other': 'ఇతర',
  },
};
